name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      outputs:
        release_id: ${{ steps.create_release.outputs.id }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create tag
        id: create_tag
        run: |
          tag=v$(date +%Y%m%d.%H%M%S)
          echo "::set-output name=tag::$tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tag }}
          draft: true
          prerelease: false
  build:
    name: Build Zip File
    needs: [release]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Use zip Utility
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
      # Make zip file of texture pack
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'FireIceResources.zip'
          exclusions: '*.git*'
      # Generate hash for zip file
      - name: Generate sha1 hash for FireIceResources.zip
        run: sha1sum FireIceResources.zip | head -c 40 > sha1hash.txt
      # Upload zip to release
      - name: Upload Resource Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: FireIceResources.zip
          asset_name: FireIceResources.zip
          asset_content_type: application/zip

      - name: Upload Zip Hash
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: sha1hash.txt
          asset_name: sha1hash.txt
          asset_content_type: application/txt
          
  metadata:
    name: Publish Release
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release.outputs.release_id }}
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 3
        remove_tags_without_release: true
