# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      outputs:
        release_id: ${{ steps.create_release.outputs.id }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: github.event_name == 'schedule'
      - name: Create tag
        id: create_tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            tag=v$(date +%Y%m%d.%H%M%S)
          else
            tag=$(basename "${{ github.ref }}")
          fi
          echo "::set-output name=tag::$tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tag }}
          draft: true
          prerelease: false
  build:
    name: Build Zip File
    needs: [release]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: action-zip
        uses: montudor/action-zip@v1.0.0

      - name: list
        run: ls 
      # Runs a single command using the runners shell
      - name: Zip output
        run: zip -qq -r FireIceResources.zip *
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: ls
      - name: Upload Resource Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: FireIceResources.zip
          asset_name: FireIceResources.zip
          asset_content_type: application/zip
          
  metadata:
    name: Publish Release
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release.outputs.release_id }}
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 3
        remove_tags_without_release: true
