name: CI 2.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Make zip file of texture pack
      - name: Compress Disasters Pack
        uses: thedoctor0/zip-release@main
        with:
          directory: 'Disasters'
          filename: '../Disasters.zip'
          exclusions: '*.git*'

      # Generate hashes for zip file
      - name: Generate sha1 hash for packs
        run: |
          sha1sum Disasters.zip | head -c 40 > Disasters.sha1
      - name: Set var of hash
        run: HASH=sha1sum Disasters.zip | head -c 40
      - name: Set sha1 hash
        env:
          PACK_HASH: sha1sum Disasters.zip | head -c 40
        run: |
          curl "https://panel.fireiceminecraft.com/api/client/servers/08f9a2b0/startup/variable" \
                  -H 'Accept: application/json' \
                  -H 'Content-Type: application/json' \
                  -H 'Authorization: Bearer ${{ secrets.DISASTERS_TOKEN }}' \
                  -X PUT \
                  -d '{ "key": "PACK_SHA1", "value": "$(PACK_HASH)" }' 

      #Update Release
      - name: Update Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto
          name: 'Auto Release $$'
          prerelease: false
          body: 'This is an automated release.'
          files: |
            ./*.sha1
            ./*.zip
