name: CI 2.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Frick up dir for zip creation
        run: cd Disasters
      # Make zip file of texture pack
      - name: Compress Disasters Pack
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: 'Disasters'
          path: '.'
          filename: '/home/runner/work/ResourcePack/ResourcePack/Disasters.zip'
          exclusions: '*.git*'
      - name: Fix dir after zip creation
        run: cd ..
      - name: Check if not a happy camper
        run: |
          pwd
          ls


      # Generate hash for zip file
      - name: Generate sha1 hash for packs
        run: sha1sum Disasters.zip | head -c 40 > Disasters.sha1
      #Update Release
      - name: Update Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto
          name: 'Resource Packs Auto Release $$'
          prerelease: false
          body: 'This is an automated release.'
          files: |
            ./Disasters.sha1
            ./Disasters.zip
